# Generated by Django 4.0.5 on 2022-06-17 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerrequestmodel',
            name='related_file',
            field=models.FileField(blank=True, null=True, upload_to='project_info_files/'),
        ),
    ]
