# Generated by Django 4.0.5 on 2022-06-17 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_post', '0002_alter_partnerrequestmodel_related_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpostmodel',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
