# Generated by Django 4.0.5 on 2022-06-17 17:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_post', '0003_alter_jobpostmodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerrequestmodel',
            name='groupName',
            field=models.CharField(default=None, max_length=30, unique=True, validators=[django.core.validators.RegexValidator(message='Need to be connected every word.', regex='^[A-Za-z][A-Za-z0-9_]{7,29}$')]),
            preserve_default=False,
        ),
    ]
