# Generated by Django 4.0.5 on 2022-06-18 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_post', '0004_partnerrequestmodel_groupname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplicationmodel',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='partnerapplicationmodel',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='partnerrequestmodel',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
