# Generated by Django 4.0.5 on 2022-08-10 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_content', '0004_syllabusmodel_connectionrequestmodel_connectionmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcastmodel',
            name='categories',
            field=models.CharField(blank=True, choices=[('Stories', 'Stories'), ('Education', 'Education'), ('Music', 'Music'), ('Coding', 'Coding'), ('Life & Goal', 'Life & Goal'), ('Business & Technology', 'Business & Technology'), ('Art & Culture', 'Art & Culture'), ('Science', 'Science'), ('Motivation', 'Motivation'), ('Health & Sports', 'Health & Sports')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='syllabusmodel',
            name='syllabus',
            field=models.FileField(upload_to='syllabuses/'),
        ),
    ]
