# Generated by Django 4.0.5 on 2022-08-11 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_content', '0006_connectionmodel_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectionrequestmodel',
            name='is_active',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
