# Generated by Django 4.0.5 on 2022-06-18 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_auth', '0002_follow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationmodel',
            name='passing_year',
            field=models.DateField(blank=True, null=True),
        ),
    ]
