# Generated by Django 4.0.5 on 2022-06-18 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_auth', '0003_alter_educationmodel_passing_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationmodel',
            name='passing_year',
            field=models.DateField(blank=True, default='2000-01-01', null=True),
        ),
    ]
