# Generated by Django 4.0.5 on 2022-06-19 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_auth', '0004_alter_educationmodel_passing_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationmodel',
            name='CGPA',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='experiencesmodel',
            name='leaving_year',
            field=models.DateField(blank=True, default='2000-01-01', null=True),
        ),
    ]
