# Generated by Django 4.0.5 on 2022-06-19 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_auth', '0005_educationmodel_cgpa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile_main',
            name='career_objective',
            field=models.CharField(default="Opportunities don't happen, You create them. ", max_length=1000),
        ),
    ]
