# Generated by Django 4.0.5 on 2022-06-19 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_auth', '0007_achievementmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='referencesmodel',
            name='created',
            field=models.DateField(default='1900-01-01'),
            preserve_default=False,
        ),
    ]
